DEPTS.PGM: depts.pgm.sqlrpgle EMPLOYEES.PGM NEWEMP.PGM DEPARTMENT.FILE DEPTS.FILE
EMPDET.MODULE: empdet.sqlrpgle EMPLOYEE.FILE DEPARTMENT.FILE
NEWEMP.PGM: newemp.pgm.sqlrpgle EMPLOYEE.FILE NEMP.FILE
EMPLOYEES.PGM: employees.pgm.sqlrpgle EMPLOYEE.FILE EMPS.FILE
MYPGM.PGM: mypgm.pgm.rpgle
EMPDET.SRVPGM: empdet.bnd EMPDET.MODULE
APP.BNDDIR: app.bnddir EMPDET.SRVPGM